services:
  db:
    image: postgres:16
    container_name: andocs_db
    restart: always
    profiles:
      - dev
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./env/db.env
    ports:
      - 5432:5432
    networks:
      - andocs-network

  redis:
    image: redis:latest
    container_name: andocs_redis
    restart: always
    profiles:
      - dev
      - default
    ports:
      - "6379:6379"
    networks:
      - andocs-network

  backend:
    build: ./services/backend
    command: python manage.py runapplication
    container_name: andocs_backend
    profiles:
      - dev
      - default
    volumes:
      - ./services/backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - ./env/backend.env
    depends_on:
      - db
      - redis
    networks:
      - andocs-network

  celeryworker:
    build: ./services/backend
    command: python manage.py runapplication --celery
    container_name: andocs_celery_worker
    profiles:
      - dev
      - default
    volumes:
      - ./services/backend:/app
    env_file:
      - ./env/backend.env
    depends_on:
      - backend
      - db
      - redis
    networks:
      - andocs-network

  celerybeat:
    build: ./services/backend
    command: python manage.py runapplication --celery-beat
    container_name: andocs_celery_beat
    volumes:
      - ./services/backend:/app
    env_file:
      - ./env/backend.env
    profiles:
      - dev
      - default
    depends_on:
      - backend
      - db
      - redis
    networks:
      - andocs-network

  frontend:
    build: ./services/frontend
    container_name: andocs_frontend
    restart: always
    volumes:
      - ./services/frontend:/app
    ports:
      - 3000:3000
    profiles:
      - dev
    networks:
      - andocs-network

  nginx:
    image: nginx:latest
    container_name: andocs_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./secrets/nginx/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./secrets/nginx/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    profiles:
      - dev
      - default
    networks:
      - andocs-network
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/nginx-selfsigned.crt
      - SSL_KEY_FILE=/etc/ssl/private/nginx-selfsigned.key
    restart: always

volumes:
  postgres_data:
    driver: local
    name: andocs_backend_postgres_data

  static_volume:
    driver: local
  
  media_volume:
    driver: local

networks:
  andocs-network:
    driver: bridge
